### Робота з бібліотекою NumPy

In [1]:
%pip install numpy
def homework(message):
    print("\n>>>>>", message, "\n")

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.6 MB 7.2 MB/s eta 0:00:02
   -------- ------------------------------- 2.6/12.6 MB 6.9 MB/s eta 0:00:02
   ----------- ---------------------------- 3.7/12.6 MB 6.4 MB/s eta 0:00:02
   ---------------- ----------------------- 5.2/12.6 MB 6.6 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.6 MB 6.9 MB/s eta 0:00:01
   -------------------------- ------------- 8.4/12.6 MB 7.0 MB/s eta 0:00:01
   ------------------------------- -------- 10.0/12.6 MB 7.2 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.6 MB 7.3 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 6.8 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
temperature = [20.1, 20.1, 20.2, 20.4]
print(temperature)

t1 = temperature * 5

print(f"При множенні на 5 маємо: {t1}")
homework("Чому маємо такий результат? \n Відповідь: Коли ви множите список Python temperature на число 5 (t1 = temperature * 5), відбувається повторення елементів списку 5 разів, а не математичне множення кожного елемента.\n Це особливість роботи зі списками в Python. Результатом є новий список, що містить вихідний список, повторений п'ять разів.")

t1 = [ x*5 for x in temperature] 
print(f"Тепер отримаємо: {t1}") 
homework("Чому тепер множення успішне? \n Відповідь: Коли ви використовуєте генератор списків [x*5 for x in temperature], кожен елемент списку temperature множиться на 5 індивідуально.\n Результат — новий список, де кожен елемент є результатом множення відповідного елемента оригінального списку.")

t2 = np.array(temperature)
print("Масив з використанням методів NumPy", t2)

t3 = t2 * 5
print("При множенні на 5 отримуємо:", t3)

[20.1, 20.1, 20.2, 20.4]
При множенні на 5 маємо: [20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4]

>>>>> Чому маємо такий результат? 
 Відповідь: Коли ви множите список Python temperature на число 5 (t1 = temperature * 5), відбувається повторення елементів списку 5 разів, а не математичне множення кожного елемента.
 Це особливість роботи зі списками в Python. Результатом є новий список, що містить вихідний список, повторений п'ять разів. 

Тепер отримаємо: [100.5, 100.5, 101.0, 102.0]

>>>>> Чому тепер множення успішне? 
 Відповідь: Коли ви використовуєте генератор списків [x*5 for x in temperature], кожен елемент списку temperature множиться на 5 індивідуально.
 Результат — новий список, де кожен елемент є результатом множення відповідного елемента оригінального списку. 

Масив з використанням методів NumPy [20.1 20.1 20.2 20.4]
При множенні на 5 отримуємо: [100.5 100.5 101.  102. ]


### Вектори, створення та робота з ними

In [ ]:
print("Все можна сторити ручну за допомогою методу np.array передавши йому набір значень у вигляді List:")
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])
print(vector_row, "\nВектор має розмір", vector_row.shape)
print(vector_column, "\nВектор має розмір", vector_column.shape)

### Метод arange - генерує послідовність чисел з певним кроком у заданому інтервалі

In [4]:

start = 5
size_of_vec = 100
x = range(size_of_vec)
a = np.arange(size_of_vec)
print(f"Масив згенерований простим range: {list(x)[0:5]} та методом arange: {a[0:5]}")
# Виведіть весь діапазон чисел.
print("Діапазон чисел згенерованого range:", list(x))
print("Діапазон чисел згенерованого arange:", a)

a = np.arange(start, size_of_vec)
print(f"Можемо задавати початок генерації вектора, перший елемент: {a[0]}")
# Виведіть останній діапазон в згенерованому масиві.
print("Останній елемент в згенерованому масиві:", a[-1])

x = range(start, size_of_vec)
print("Те саме але з вбудованою функцією range:", x)
print("Власне вивід значень:", list(x)[0])
# Виведіть якесь число з середини діапазону.
print("Число з середини діапазону:", list(x)[len(x) // 2])

# Дробові числа
x = np.arange(10.4)
print("Будем мати:", x)

# Крок
x = np.arange(0.5, 4, 0.5)
print("З кроком 0.5:", x)

# Заокруглення
x = np.arange(0.04, 1.84, 0.08)
print("З кроком 0.08:", x, "\nЗверніть увагу на заокруглення.")
# Згенеруйте значення де крок буде мати чотири нулі після коми, яким буде результат?
x = np.arange(0.0001, 0.001, 0.0001)
print("Згенеровані значення з кроком 0.0001:", x)

y = x * 2.5
print("Після перемноження:", y)
# Піднесіть отримане число до степеня та поділіть на 0.4 - Яким буде результат?
y = y**2 / 0.4
print("Після піднесення до квадрату і ділення на 0.4:", y)

Масив згенерований простим range: [0, 1, 2, 3, 4] та методом arange: [0 1 2 3 4]
Діапазон чисел згенерованого range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
Діапазон чисел згенерованого arange: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Можемо задавати початок генерації вектора, перший елемент: 5
Останній елемент в згенерованому масиві: 99
Те саме але з вбудованою функцією range: ran

### Метод linspace - генерує задану кількістю чисел у певному діапазоні, 50 чисел за замовчуванням

In [5]:
a = np.linspace(start, size_of_vec)
print(f"Згенерували {len(a)} чисел в діапазоні {a[0]} до {a[-1]}")

# Вивести кожне друге число згенерованого діапазону за допомогою циклу
print("Кожне друге число згенерованого діапазону:")
for i in range(1, len(a), 2):
    print(a[i])

print("Можна зменшити кількість чисел до 5:")
a = np.linspace(start, size_of_vec, 5)
print(a)
# Збільшіть кількість чисел до 100. Виведіть перших та останніх 10.
a = np.linspace(start, size_of_vec, 100)
print(f"Перші 10 чисел: {a[:10]}")
print(f"Останні 10 чисел: {a[-10:]}")

print("""Як бачимо перше та останнє значення завжди входять у згенерований діапазон. 
Відповідно при цьому вираховується крок.
Це можна змінити, виключивши останнє значення з визначення діапазону.
""")

print(np.linspace(start, size_of_vec, 5, endpoint=False))
# Спробуйте самі порахувати крок.
print("Крок у linspace без включення кінцевого значення:", np.linspace(start, size_of_vec, 5, endpoint=False)[1] - np.linspace(start, size_of_vec, 5, endpoint=False)[0])

_, sp_1 = np.linspace(start, size_of_vec, 5, endpoint=True, retstep=True)
_, sp_2 = np.linspace(start, size_of_vec, 5, endpoint=False, retstep=True)
print(f"Для порівняння, ми можемо визначити крок автоматично, у нашому випадку це {sp_1} та {sp_2}")
# Чому маємо такий крок?
print(f"Крок в першому випадку (з endpoint=True): {sp_1}, а в другому випадку (з endpoint=False): {sp_2}. Крок змінюється через те, чи включено кінцеве значення в діапазон.")


Згенерували 50 чисел в діапазоні 5.0 до 100.0
Кожне друге число згенерованого діапазону:
6.938775510204081
10.816326530612244
14.693877551020408
18.57142857142857
22.448979591836736
26.3265306122449
30.20408163265306
34.08163265306122
37.95918367346939
41.83673469387755
45.714285714285715
49.59183673469388
53.46938775510204
57.3469387755102
61.224489795918366
65.10204081632654
68.9795918367347
72.85714285714286
76.73469387755102
80.61224489795919
84.48979591836735
88.36734693877551
92.24489795918367
96.12244897959184
100.0
Можна зменшити кількість чисел до 5:
[  5.    28.75  52.5   76.25 100.  ]
Перші 10 чисел: [ 5.          5.95959596  6.91919192  7.87878788  8.83838384  9.7979798
 10.75757576 11.71717172 12.67676768 13.63636364]
Останні 10 чисел: [ 91.36363636  92.32323232  93.28282828  94.24242424  95.2020202
  96.16161616  97.12121212  98.08080808  99.04040404 100.        ]
Як бачимо перше та останнє значення завжди входять у згенерований діапазон. 
Відповідно при цьому вираховуєть

# Ось завдання нормально виконане без циклу

In [6]:
a = np.linspace(start, size_of_vec)
print(f"Згенерували {len(a)} чисел в діапазоні {a[0]} до {a[-1]}")
# Вивести кожне друге число згенерованого діапазону.
print("Кожне друге число згенерованого діапазону:", a[::2])

print("Можна зменшити кількість чисел до 5:")
a = np.linspace(start, size_of_vec, 5)
print(a)
# Збільшіть кількість чисел до 100. Виведіть перших та останніх 10.
a = np.linspace(start, size_of_vec, 100)
print(f"Перші 10 чисел: {a[:10]}")
print(f"Останні 10 чисел: {a[-10:]}")

print("""Як бачимо перше та останнє значення завжди входять у згенерований діапазон. 
Відповідно при цьому вираховується крок.
Це можна змінити, виключивши останнє значення з визначення діапазону.
""")

print(np.linspace(start, size_of_vec, 5, endpoint=False))
# Спробуйте самі порахувати крок.
print("Крок у linspace без включення кінцевого значення:", np.linspace(start, size_of_vec, 5, endpoint=False)[1] - np.linspace(start, size_of_vec, 5, endpoint=False)[0])

_, sp_1 = np.linspace(start, size_of_vec, 5, endpoint=True, retstep=True)
_, sp_2 = np.linspace(start, size_of_vec, 5, endpoint=False, retstep=True)
print(f"Для порівняння, ми можемо визначити крок автоматично, у нашому випадку це {sp_1} та {sp_2}")
# Чому маємо такий крок?
print(f"Крок в першому випадку (з endpoint=True): {sp_1}, а в другому випадку (з endpoint=False): {sp_2}. Крок змінюється через те, чи включено кінцеве значення в діапазон.")


Згенерували 50 чисел в діапазоні 5.0 до 100.0
Кожне друге число згенерованого діапазону: [ 5.          8.87755102 12.75510204 16.63265306 20.51020408 24.3877551
 28.26530612 32.14285714 36.02040816 39.89795918 43.7755102  47.65306122
 51.53061224 55.40816327 59.28571429 63.16326531 67.04081633 70.91836735
 74.79591837 78.67346939 82.55102041 86.42857143 90.30612245 94.18367347
 98.06122449]
Можна зменшити кількість чисел до 5:
[  5.    28.75  52.5   76.25 100.  ]
Перші 10 чисел: [ 5.          5.95959596  6.91919192  7.87878788  8.83838384  9.7979798
 10.75757576 11.71717172 12.67676768 13.63636364]
Останні 10 чисел: [ 91.36363636  92.32323232  93.28282828  94.24242424  95.2020202
  96.16161616  97.12121212  98.08080808  99.04040404 100.        ]
Як бачимо перше та останнє значення завжди входять у згенерований діапазон. 
Відповідно при цьому вираховується крок.
Це можна змінити, виключивши останнє значення з визначення діапазону.

[ 5. 24. 43. 62. 81.]
Крок у linspace без включення кін

### Типи масивів/векторів

In [16]:
import numpy as np

examples = {
    'Скаляр': np.array(1),
    'Вектор Рядок': np.array([1, 2, 3]),
    'Вектор Стовпець': np.array([[1], [2], [3]]),
    'Матриця': np.array([[1, 2], [3, 4], [5, 6]]),
    'Багатовимірна Матриця': np.array([[[111, 112], [121, 122]],
                                       [[211, 212], [221, 222]],
                                       [[311, 312], [321, 322]]])
}

for key in examples:
    print(f"Розглядаємо приклад з {key}. \nЗначення x буде: \n", examples[key])
    print(f"Тип {key} x: ", type(examples[key]))
    print(f"Розмірність/вимір {key} x:", np.ndim(examples[key]))
    print(f"Форма {key} x: ", examples[key].shape)
    print(f"Кількість елементів х: {np.size(examples[key])}")
    print("-=-" * 10)

# Homework
homework("""
Як Ви думаєте чому маємо такий результат для функції np.ndim (Розмірність/вимір/dimension)?
Чому значення для векторів та матриць однакове та не співпадає з значенням shape?
Задайте власні вектори з різними числами.
""")
# Відповідь на запитання
print("Відповідь на запитання: np.ndim повертає кількість осей масиву. Для скаляра це 0, для вектора 1, для матриці 2 і т.д.\n Значення np.ndim для векторів та матриць однакове, тому що функція просто підраховує кількість вимірів,\n а не кількість елементів у масиві. Вектор (рядок) і вектор (стовпець) мають по одному виміру, але їх форма різна.")

# Приклад власних векторів:
vektor1 = np.array([10, 20, 30])  # Вектор 1
vektor2 = np.array([[5], [10]])  # Вектор 2 (стовпець)
print("Тип вектора1:", np.ndim(vektor1), "Форма:", vektor1.shape)
print("Тип вектора2:", np.ndim(vektor2), "Форма:", vektor2.shape)


Розглядаємо приклад з Скаляр. 
Значення x буде: 
 1
Тип Скаляр x:  <class 'numpy.ndarray'>
Розмірність/вимір Скаляр x: 0
Форма Скаляр x:  ()
Кількість елементів х: 1
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Вектор Рядок. 
Значення x буде: 
 [1 2 3]
Тип Вектор Рядок x:  <class 'numpy.ndarray'>
Розмірність/вимір Вектор Рядок x: 1
Форма Вектор Рядок x:  (3,)
Кількість елементів х: 3
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Вектор Стовпець. 
Значення x буде: 
 [[1]
 [2]
 [3]]
Тип Вектор Стовпець x:  <class 'numpy.ndarray'>
Розмірність/вимір Вектор Стовпець x: 2
Форма Вектор Стовпець x:  (3, 1)
Кількість елементів х: 3
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Матриця. 
Значення x буде: 
 [[1 2]
 [3 4]
 [5 6]]
Тип Матриця x:  <class 'numpy.ndarray'>
Розмірність/вимір Матриця x: 2
Форма Матриця x:  (3, 2)
Кількість елементів х: 6
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Багатовимірна Матриця. 
Значення x буде: 
 [[[111 112]
  [121 122]]

 [[211 

### Багатовимірні масиви, розуміння вимірів

In [14]:
import numpy as np
examples = {
    '5 рядків': np.array([[1], [2], [3], [4], [5]]), 
    '5 стовпців': np.array([[1, 2, 3, 4, 5]]),
    '5 елементів': np.array([[[1, 2, 3, 4, 5]]])
}
for a in examples:
    print(f"Для {a} маємо shape: \n{examples[a].shape} \nта вигляд: \n{examples[a]}\n")

# Homework
homework(f"Створіть власні масиви з різною кількістю елементів та використайте метод shape для визначення їх вимірів.")
homework_examples = {
    '1 рядок, 3 стовпці': np.array([[1, 2, 3]]), 
    '3 рядки, 1 стовпець': np.array([[1], [2], [3]]),
    '2 рядки, 2 стовпці': np.array([[1, 2], [3, 4]]),
    '1 елемент': np.array([7]),
    '3 елементи': np.array([1, 2, 3])
}

# Виведення форми та вигляду додаткових масивів
for description, array in homework_examples.items():
    print(f"Для {description} маємо shape: \n{array.shape} \nта вигляд: \n{array}\n")


Для 5 рядків маємо shape: 
(5, 1) 
та вигляд: 
[[1]
 [2]
 [3]
 [4]
 [5]]

Для 5 стовпців маємо shape: 
(1, 5) 
та вигляд: 
[[1 2 3 4 5]]

Для 5 елементів маємо shape: 
(1, 1, 5) 
та вигляд: 
[[[1 2 3 4 5]]]


>>>>> Створіть власні масиви з різною кількістю елементів та використайте метод shape для визначення їх вимірів. 

Для 1 рядок, 3 стовпці маємо shape: 
(1, 3) 
та вигляд: 
[[1 2 3]]

Для 3 рядки, 1 стовпець маємо shape: 
(3, 1) 
та вигляд: 
[[1]
 [2]
 [3]]

Для 2 рядки, 2 стовпці маємо shape: 
(2, 2) 
та вигляд: 
[[1 2]
 [3 4]]

Для 1 елемент маємо shape: 
(1,) 
та вигляд: 
[7]

Для 3 елементи маємо shape: 
(3,) 
та вигляд: 
[1 2 3]



### Indexing and Slicing

In [11]:
import numpy as np
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
print(f"""Масив: {F}
Виміри: {F.shape}
Пам'ятаємо, що номерація масивів відбувається з 0.
Тому перший елемент масиву:
 {F[0]}
Другий:
 {F[1]}
Останній, {len(F)}: 
 {F[7]}""")

print(f"""Можемо скористатись від'ємними індексами, якщо хочемо доступитись до елементів з кінця масиву.
Але номерація вже з 1.
Тому останній елемент:
 {F[-1]}
Передостанній:
 {F[-2]}""")

#Homework
homework("Попрактикуйтесь доступатись до елементів, виведіть декілька елементів різними способами.")
# Попрактикуємось доступатись до елементів різними способами
print(f"""Доступ до елементів через зрізи:
Перші три елементи масиву:
 {F[:3]}
Кожен другий елемент:
 {F[::2]}
Елементи з 3-го по 6-й:
 {F[2:6]}""")




Масив: [ 1  1  2  3  5  8 13 21]
Виміри: (8,)
Пам'ятаємо, що номерація масивів відбувається з 0.
Тому перший елемент масиву:
 1
Другий:
 1
Останній, 8: 
 21
Можемо скористатись від'ємними індексами, якщо хочемо доступитись до елементів з кінця масиву.
Але номерація вже з 1.
Тому останній елемент:
 21
Передостанній:
 13

>>>>> Попрактикуйтесь доступатись до елементів, виведіть декілька елементів різними способами. 

Доступ до елементів через зрізи:
Перші три елементи масиву:
 [1 1 2]
Кожен другий елемент:
 [ 1  2  5 13]
Елементи з 3-го по 6-й:
 [2 3 5 8]


In [12]:
import numpy as np
A = np.array([ [3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8],
               [7.0, -3.9, 5.1]])

# Виведення масиву та доступ до елементів
print(f"""Масив:
{A}
Виміри: {A.shape}
Принцип номерації такий самий, ТІЛЬКИ:
Якщо задати одне значення то візьметься цілий рядок:
    Перший рядок: {A[0]}
    Останній рядок: {A[-1]}
Для того щоб взяти цілий стовпець (символ : вказує взяти всі елементи): 
    Перший стовпець: {A[:,0]}
    Останній стовпець: {A[:,-1]}
Потрібно задавати два значення для отримання конкретного елемента: 
    Перший елемент: {A[0][0]} або {A[0, 0]}
    Останній елемент: {A[3][2]} або {A[-1][-1]} або {A[3, -1]}
""")

# Homework
homework("Попрактикуйтесь в доступі до багатовимірного масиву, виведіть елементів які належать діагоналі.")
print(f"""Елементи на діагоналі:
Перший елемент діагоналі: {A[0, 0]}
Другий елемент діагоналі: {A[1, 1]}
Третій елемент діагоналі: {A[2, 2]}
Останній елемент діагоналі: {A[3, 0]} (якщо б масив був квадратним, це був би останній елемент діагоналі)""")

# Альтернативний спосіб отримати всі елементи діагоналі:
diagonal_elements = np.diagonal(A)
print(f"Всі елементи діагоналі: {diagonal_elements}")


Масив:
[[ 3.4  8.7  9.9]
 [ 1.1 -7.8 -0.7]
 [ 4.1 12.3  4.8]
 [ 7.  -3.9  5.1]]
Виміри: (4, 3)
Принцип номерації такий самий, ТІЛЬКИ:
Якщо задати одне значення то візьметься цілий рядок:
    Перший рядок: [3.4 8.7 9.9]
    Останній рядок: [ 7.  -3.9  5.1]
Для того щоб взяти цілий стовпець (символ : вказує взяти всі елементи): 
    Перший стовпець: [3.4 1.1 4.1 7. ]
    Останній стовпець: [ 9.9 -0.7  4.8  5.1]
Потрібно задавати два значення для отримання конкретного елемента: 
    Перший елемент: 3.4 або 3.4
    Останній елемент: 5.1 або 5.1 або 5.1


>>>>> Попрактикуйтесь в доступі до багатовимірного масиву, виведіть елементів які належать діагоналі. 

Елементи на діагоналі:
Перший елемент діагоналі: 3.4
Другий елемент діагоналі: -7.8
Третій елемент діагоналі: 4.8
Останній елемент діагоналі: 7.0 (якщо б масив був квадратним, це був би останній елемент діагоналі)
Всі елементи діагоналі: [ 3.4 -7.8  4.8]


In [15]:
import numpy as np
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(f"""Масив:
{S}
Виміри: {S.shape}
Беремо декілька елементів: {S[2:5]}
Всі елементи до заданого: {S[:4]}
Всі елементи від заданого до кінця: {S[6:]}
Всі елементи: {S[:]}
""")

# Homework
homework("Попрактикуйтесь у витягуванні елементів, візьміть 4 значення з кінця масиву.")
last_four_elements = S[-4:]
print(f"Останні 4 елементи масиву: {last_four_elements}")


Масив:
[0 1 2 3 4 5 6 7 8 9]
Виміри: (10,)
Беремо декілька елементів: [2 3 4]
Всі елементи до заданого: [0 1 2 3]
Всі елементи від заданого до кінця: [6 7 8 9]
Всі елементи: [0 1 2 3 4 5 6 7 8 9]


>>>>> Попрактикуйтесь у витягуванні елементів, візьміть 4 значення з кінця масиву. 

Останні 4 елементи масиву: [6 7 8 9]


In [17]:
import numpy as np
A = np.array([
    [11, 12, 13, 14, 15],
    [21, 22, 23, 24, 25],
    [31, 32, 33, 34, 35],
    [41, 42, 43, 44, 45],
    [51, 52, 53, 54, 55]
])
print(f"""Масив:
{A}
Виміри: {A.shape}
Беремо декілька рядків: 
{A[0:2]}
Два перші стовпці: 
{A[:, 0:2]}
Два останні рядки:
{A[3:, :]}
Беремо підматрицю (нижні елементи): 
{A[-3:, -3:]}
""")

# Homeworkk
homework("Попрактикуйтесь у витягуванні елементів, візьміть матрицю 2х2 з нижнього та верхнього кутка матриці А.")
upper_left = A[:2, :2]  # Верхній лівий кут
lower_right = A[-2:, -2:]  # Нижній правий кут

print(f"Матриця 2x2 з верхнього лівого кута: \n{upper_left}")
print(f"Матриця 2x2 з нижнього правого кута: \n{lower_right}")


Масив:
[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]
Виміри: (5, 5)
Беремо декілька рядків: 
[[11 12 13 14 15]
 [21 22 23 24 25]]
Два перші стовпці: 
[[11 12]
 [21 22]
 [31 32]
 [41 42]
 [51 52]]
Два останні рядки:
[[41 42 43 44 45]
 [51 52 53 54 55]]
Беремо підматрицю (нижні елементи): 
[[33 34 35]
 [43 44 45]
 [53 54 55]]


>>>>> Попрактикуйтесь у витягуванні елементів, візьміть матрицю 2х2 з нижнього та верхнього кутка матриці А. 

Матриця 2x2 з верхнього лівого кута: 
[[11 12]
 [21 22]]
Матриця 2x2 з нижнього правого кута: 
[[44 45]
 [54 55]]


In [18]:
import numpy as np
A = np.arange(28).reshape(4, 7)

print(f"""Масив:
{A}
Виміри: {A.shape}
Беремо кожен другий елемент першого рядка: 
{A[0, ::2]}
Беремо кожен третій елемент першого рядка: 
{A[0, ::3]}
Кожен другий елемент в кожному другому рядку: 
{A[::2, ::2]}
Останні три елементи в кожному другому рядку:
{A[::2, 4:]}
Можна повністю змінити порядок елементів (дзеркально обернемо):
{A[::-1, ::-1]}
""")

# Homework
homework("Попрактикуйтесь у витягуванні елементів, будь-яка робоча комбінація.")
combination_1 = A[1, 2:5]  # Третій, четвертий та п'ятий елементи другого рядка
combination_2 = A[::2, 1::3]  # Кожен другий стовпець з непарних рядків
combination_3 = A[2, ::2]  # Кожен другий елемент третього рядка

print(f"Комбінація 1 (елементи другого рядка, з 3 по 5): \n{combination_1}")
print(f"Комбінація 2 (елементи з непарних рядків і кожен третій стовпець): \n{combination_2}")
print(f"Комбінація 3 (кожен другий елемент третього рядка): \n{combination_3}")


Масив:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
Виміри: (4, 7)
Беремо кожен другий елемент першого рядка: 
[0 2 4 6]
Беремо кожен третій елемент першого рядка: 
[0 3 6]
Кожен другий елемент в кожному другому рядку: 
[[ 0  2  4  6]
 [14 16 18 20]]
Останні три елементи в кожному другому рядку:
[[ 4  5  6]
 [18 19 20]]
Можна повністю змінити порядок елементів (дзеркально обернемо):
[[27 26 25 24 23 22 21]
 [20 19 18 17 16 15 14]
 [13 12 11 10  9  8  7]
 [ 6  5  4  3  2  1  0]]


>>>>> Попрактикуйтесь у витягуванні елементів, будь-яка робоча комбінація. 

Комбінація 1 (елементи другого рядка, з 3 по 5): 
[ 9 10 11]
Комбінація 2 (елементи з непарних рядків і кожен третій стовпець): 
[[ 1  4]
 [15 18]]
Комбінація 3 (кожен другий елемент третього рядка): 
[14 16 18 20]


In [19]:
import numpy as np
A = np.arange(50)

all_even = (A % 2 == 0)  # парні числа
complex_condition = (A < 30) & (A / 5 < 2)  # складніша умова
print(f"""Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або {all_even[0]} для {A[0]} або {all_even[1]} для {A[1]}.
Після підставляння умови пошуку парних чисел в масив отримаємо:
{A[all_even]}
Або застосувати більш комплексну умову з двох порівнянь:
{A[complex_condition]}
""")

# Homeworkw
homework("Виведіть всі непарні числа з даного масиву.")
all_odd = (A % 2 != 0)  # непарні числа
print(f"Всі непарні числа: {A[all_odd]}")


Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або True для 0 або False для 1.
Після підставляння умови пошуку парних чисел в масив отримаємо:
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
Або застосувати більш комплексну умову з двох порівнянь:
[0 1 2 3 4 5 6 7 8 9]


>>>>> Виведіть всі непарні числа з даного масиву. 

Всі непарні числа: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


### Функції для створення матриць: ones, zeros, identity, eye, empty

In [20]:
o = np.ones(5)
z = np.zeros(5)
i = np.identity(5)
e = np.eye(5)
t = np.empty(5)

print(f"""
Всі елементи 1:
{o}
Всі елементи 0:
{z}
Матриця в якої діагональ всі 1:
{i}
Також, діагональ всі 1 (зменшимо вивід):
{e[:2, :2]}
Пуста матриця буде містити набір випадкових чисел які записані у память де був ініціалізований масив:
{t}
""")



Всі елементи 1:
[1. 1. 1. 1. 1.]
Всі елементи 0:
[0. 0. 0. 0. 0.]
Матриця в якої діагональ всі 1:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Також, діагональ всі 1 (зменшимо вивід):
[[1. 0.]
 [0. 1.]]
Пуста матриця буде містити набір випадкових чисел які записані у память де був ініціалізований масив:
[4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323]

