# Операції над масивами

In [1]:
def homework(message):
    print("\n>>>>>", message, "\n")
import numpy as np

In [5]:
l = (3, 3)

O = np.ones(l)
R = np.random.random(l)
Z = np.zeros(l)
C = np.arange(l[0])

print(f"""
Віднімання:\n {C - (O + 10)}
Множення:\n {O * R}
Ділення:\n {R / C}
Степінь:\n {C ** Z}
Поріняння:\n {R > 0.5}
Ділення на 0:\n {O / Z}
""")

# Homework
homework("""
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де цетнтральні діагональ все нулі).
""")
E = np.eye(3)  # Створення одиничної матриці
comparison = E == 1  # Порівняння на наявність 1

# Створення матриці ones та віднімання матриці eye
ones_minus_eye = np.ones((3, 3)) - np.eye(3)

# Виведення результатів
print(f"""
Одинична матриця:\n{E}
Порівняння на наявність 1:\n{comparison}
Результат ones - eye:\n{ones_minus_eye}
""")


Віднімання:
 [[-11. -10.  -9.]
 [-11. -10.  -9.]
 [-11. -10.  -9.]]
Множення:
 [[0.25793105 0.91085035 0.70858585]
 [0.96916342 0.39710424 0.77175337]
 [0.22838    0.08898784 0.72133483]]
Ділення:
 [[       inf 0.91085035 0.35429293]
 [       inf 0.39710424 0.38587668]
 [       inf 0.08898784 0.36066742]]
Степінь:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Поріняння:
 [[False  True  True]
 [ True False  True]
 [False False  True]]
Ділення на 0:
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]

Завдання: 
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де цетнтральні діагональ все нулі).


Одинична матриця:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Порівняння на наявність 1:
[[ True False False]
 [False  True False]
 [False False  True]]
Результат ones - eye:
[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]



C:\Users\user\AppData\Local\Temp\ipykernel_28404\2527746806.py:11: RuntimeWarning: divide by zero encountered in divide
  Ділення:\n {R / C}
C:\Users\user\AppData\Local\Temp\ipykernel_28404\2527746806.py:14: RuntimeWarning: divide by zero encountered in divide
  Ділення на 0:\n {O / Z}


# Множення матриць

In [6]:
A = np.array([ [1, 2, 3], [2, 2, 2], [3, 3, 3] ])
B = np.array([ [3, 2, 1], [1, 2, 3], [-1, -2, -3] ])
print(f"Маємо два масиви:\n {A} \n {B}")

R = A * B
print(f"Тут виконується поелементне множення:\n {R}")

R = np.dot(A, B)
print(f"Тут, масиви перемножуються як матриці:\n {R}")

MA = np.mat(A)
MB = np.mat(B)

R = MA * MB
print(f"Тут масиви перетворені на матриці і далі перемножуються:\n {R}")

Маємо два масиви:
 [[1 2 3]
 [2 2 2]
 [3 3 3]] 
 [[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]
Тут виконується поелементне множення:
 [[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]
Тут, масиви перемножуються як матриці:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]


AttributeError: `np.mat` was removed in the NumPy 2.0 release. Use `np.asmatrix` instead.

# Виправлений код
> У версії NumPy 2.0 метод np.mat був видалений. Замість нього слід використовувати np.asmatrix.

In [15]:
import numpy as np

A = np.array([[1, 2, 3], [2, 2, 2], [3, 3, 3]])
B = np.array([[3, 2, 1], [1, 2, 3], [-1, -2, -3]])
print(f"Маємо два масиви:\n {A} \n {B}")

R = A * B
print(f"Тут виконується поелементне множення:\n {R}")

R = np.dot(A, B)
print(f"Тут масиви перемножуються як матриці:\n {R}")

MA = np.asmatrix(A)
MB = np.asmatrix(B)

R = MA * MB
print(f"Тут масиви перетворені на матриці і далі перемножуються:\n {R}")


Маємо два масиви:
 [[1 2 3]
 [2 2 2]
 [3 3 3]] 
 [[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]
Тут виконується поелементне множення:
 [[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]
Тут масиви перемножуються як матриці:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]
Тут масиви перетворені на матриці і далі перемножуються:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]


# Вирівнювання розмірностей

In [7]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
C = B[:, np.newaxis]

print(f"Вектор В є рядком {B.shape}: {B} тому додавання буде по рядках:\n {A + B}")

print(f"""Вектор C є стовпцем {C.shape}:
{C}
тому додавання буде по стовпцям:
{A + C}""")

print(f"У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:\n {B + C}")

Вектор В є рядком (3,): [1 2 3] тому додавання буде по рядках:
 [[12 14 16]
 [22 24 26]
 [32 34 36]]
Вектор C є стовпцем (3, 1):
[[1]
 [2]
 [3]]
тому додавання буде по стовпцям:
[[12 13 14]
 [23 24 25]
 [34 35 36]]
У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


# Конкатенація, повторення та зміна форми (shape)
> Тут я звернувся до допомоги Chat GPT, тому що трішки не зрозумів як правильно виконати Завдання 2.
>> Основні зміни:
>>> Виправлено N.reshape((2, 3)): для коректності використовується масив з однаковою кількістю елементів.

>>> У Завданні 2 додано створення нового масиву для сумісного розміру.

>>> Додано перевірку при виконанні reshape.

In [13]:
import numpy as np

# Вихідні масиви
D = np.ones(3)
Z = np.zeros((3, 1))
B = np.ones((3, 3))
C = np.zeros((3, 1))
A = np.arange(12).reshape((3, 4))

# Демонстрація операцій
print(f"""
При конкатенації рядків маємо: {np.concatenate((D, D))}
При конкатенації стовпців маємо:\n{np.concatenate((Z, Z), axis=1)}
Масив D {D} має розмірність {D.shape}, тому може виконати операцію конкатенації з B {B} розмірністю {B.shape}:
{np.concatenate((B, D.reshape((1, 3))), axis=0)}
Для конкатенації з C:
{C}
де C має розмірність = {C.shape}, потрібно змінити розмірність D = {D.shape}.
Це можна зробити ось так:
{D[:, np.newaxis].shape}
або
{D.reshape((3, 1)).shape}.
У результаті ми можемо виконати конкатенацію:
{np.concatenate((C, D.reshape((3, 1))), axis=1)}
При повторенні D {D} 2 рази для рядків та 3 для стовпців будемо мати:
{np.tile(D, (2, 3))}
Як бачимо, конкатенація та повторення є дещо схожими у деяких випадках:
- конкатенація: {np.concatenate((D, D))}
- повторення: {np.tile(D, 2)}
Також можна перетворити двовимірний масив A розмірністю {A.shape} на рядок: {A.flatten()} з розмірністю {A.flatten().shape}.
""")

# Homework 
homework(f"""
1. Створіть двовимірний масив за допомогою arange та виконайте конкатенацію та повторення.
2. Створіть масив, у якому кількість рядків і стовпців різна. Спробуйте виконати конкатенацію такого масиву з попереднім. Якщо розмірність масивів не співпадає, використайте reshape.
3. Створіть декілька двовимірних масивів із сумарною розмірністю 12 та знайдіть усі можливі комбінації reshape. Наприклад, перша комбінація — це рядок: {np.ones((1, 12))}.
""")

# Завдання 1
print("Завдання 1:")
M = np.arange(6).reshape((2, 3))
print(f"Двовимірний масив:\n{M}")
print(f"Конкатенація:\n{np.concatenate((M, M), axis=0)}")
print(f"Повторення:\n{np.tile(M, (2, 1))}")

# Завдання 2
print("Завдання 2:")
N = np.arange(9).reshape((3, 3))
print(f"Масив N:\n{N}")
try:
    print(f"Конкатенація з M:\n{np.concatenate((M, N), axis=1)}")
except ValueError as e:
    print(f"Помилка через різні розміри: {e}")
    # Підлаштовуємо розмір M для конкатенації
    M_reshaped = np.arange(9).reshape((3, 3))
    print(f"Конкатенація після зміни розміру M:\n{np.concatenate((M_reshaped, N), axis=0)}")

# Завдання 3
print("Завдання 3:")
all_combinations = []
array = np.arange(12)
for i in range(1, 13):
    if 12 % i == 0:
        reshaped = array.reshape((i, 12 // i))
        all_combinations.append(reshaped)
        print(f"Комбінація {i}x{12 // i}:\n{reshaped}")



При конкатенації рядків маємо: [1. 1. 1. 1. 1. 1.]
При конкатенації стовпців маємо:
[[0. 0.]
 [0. 0.]
 [0. 0.]]
Масив D [1. 1. 1.] має розмірність (3,), тому може виконати операцію конкатенації з B [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] розмірністю (3, 3):
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Для конкатенації з C:
[[0.]
 [0.]
 [0.]]
де C має розмірність = (3, 1), потрібно змінити розмірність D = (3,).
Це можна зробити ось так:
(3, 1)
або
(3, 1).
У результаті ми можемо виконати конкатенацію:
[[0. 1.]
 [0. 1.]
 [0. 1.]]
При повторенні D [1. 1. 1.] 2 рази для рядків та 3 для стовпців будемо мати:
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Як бачимо, конкатенація та повторення є дещо схожими у деяких випадках:
- конкатенація: [1. 1. 1. 1. 1. 1.]
- повторення: [1. 1. 1. 1. 1. 1.]
Також можна перетворити двовимірний масив A розмірністю (3, 4) на рядок: [ 0  1  2  3  4  5  6  7  8  9 10 11] з розмірністю (12,).

Завдання: 
1. Створіть двовимірний масив за допомого

# Трансформації масивів

In [14]:
import numpy as np
O = np.arange(6).reshape(3,2)
O_r = O.reshape((2,3))
O_f = O.flatten()
O_t = O.transpose()
O_fl = np.flip(O)
O_fa = np.flip(O, axis=1)

print(f"""{O}
Змінити розмірність shape {O.shape} на {O_r.shape} при цьому розмір size {O.size} = {O_r.size} та ndim {np.ndim(O)} = {np.ndim(O_r)}:
{O_r}
Також можна перетворити {np.ndim(O)}-х вимірний масив розмірністю {O.shape} на рядок:
{O_f} 
з розмірністю {O_f.shape} при цьому size = {O_f.size} та ndim стане {np.ndim(O_f)}-х вимірним 
Або транспонувати масив щоб він став {O_t.shape} але зверніть увагу на елементи:
{O_t}
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
{O_fl}
Або обернути лише елементи в кожному рядку (або стовпці):
{O_fa}
""")

#Homework
homework("""
- 1. Створіть вектор з 12 елементів, визначте його shape, size та ndim;
- 2. Змініть розмірніть перетворивши вектор у матрицю;
- 3. Здійсніть транспонування отриманої матриці та оберніть її;
- 4. Перетворіть отриманий багатовимірний масив назад у вектор (стрічку);
""")

print("Завдання 1: ")
vector = np.arange(12)
print(f"Вектор:\n{vector}\nShape: {vector.shape}, Size: {vector.size}, Ndim: {vector.ndim}")

print("Завдання 2: ")
matrix = vector.reshape(3, 4)
print(f"Матриця:\n{matrix}\nShape: {matrix.shape}, Size: {matrix.size}, Ndim: {matrix.ndim}")

print("Завдання 3: ")
transposed_matrix = matrix.transpose()
print(f"Транспонована матриця:\n{transposed_matrix}\nShape: {transposed_matrix.shape}")
flipped_matrix = np.flip(transposed_matrix)
print(f"Обернена матриця:\n{flipped_matrix}")

print("Завдання 4: ")
flattened_back = flipped_matrix.flatten()
print(f"Перетворена назад у вектор (стрічка):\n{flattened_back}\nShape: {flattened_back.shape}, Size: {flattened_back.size}, Ndim: {flattened_back.ndim}")

[[0 1]
 [2 3]
 [4 5]]
Змінити розмірність shape (3, 2) на (2, 3) при цьому розмір size 6 = 6 та ndim 2 = 2:
[[0 1 2]
 [3 4 5]]
Також можна перетворити 2-х вимірний масив розмірністю (3, 2) на рядок:
[0 1 2 3 4 5] 
з розмірністю (6,) при цьому size = 6 та ndim стане 1-х вимірним 
Або транспонувати масив щоб він став (2, 3) але зверніть увагу на елементи:
[[0 2 4]
 [1 3 5]]
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
[[5 4]
 [3 2]
 [1 0]]
Або обернути лише елементи в кожному рядку (або стовпці):
[[1 0]
 [3 2]
 [5 4]]

Завдання: 
- 1. Створіть вектор з 12 елементів, визначте його shape, size та ndim;
- 2. Змініть розмірніть перетворивши вектор у матрицю;
- 3. Здійсніть транспонування отриманої матриці та оберніть її;
- 4. Перетворіть отриманий багатовимірний масив назад у вектор (стрічку);

Завдання 1: 
Вектор:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,), Size: 12, Ndim: 1
Завдання 2: 
Матриця:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4), Size: